### ISSUE TITLE
How to call the backend api to implement rss

### ISSUE THREAD

**Issue by wangrunze2023** [tresko/nuxt-module-feed#43]
The project does not use Nitro Hooks, but calls the api interface of the back-end program to obtain list information. How should I use it to generate feed.xml?

**Comment by tresko** [comment]
Create a nitro plugin like here in the playground example. https://github.com/tresko/nuxt-module-feed/blob/main/playground/server/plugins/feed.ts. You can call the backend here. 

I must take a look if we could use nitro hooks in the future.
